### ISSUE TITLE
Acreom does not uninstall completely

### ISSUE THREAD

**Issue by indig0F10w** [Acreom/app#6]
There is not a single "Next" on installation or uninstallation. It just installs without any prompt and uninstall without any prompt. Leaves 160MB of useless files and acreom-assistant.exe seems to run from time to time.

![Acreom](https://github.com/user-attachments/assets/1b9780d3-b82c-4c27-b4a9-a0af86018bc2)

**Comment by hackal** [comment]
Thanks for the report. I have updated electron-builder to delete app data on uninstall. See more info at https://www.electron.build/nsis#deleteappdataonuninstall
